### ISSUE TITLE
Multi-Module Gradle configuration issue

### ISSUE THREAD

**Issue by martinbonnin** [apollographql/apollo-kotlin#4443]
Follow up from https://github.com/apollographql/apollo-kotlin/issues/3297. 

Latest comment from @Drjacky :

I have used
```kotlin
apollo {
  packageName.set("com.example....")
}
...
    implementation(project(Depends.Common.models))
    apolloMetadata(project(Depends.Common.models))
```
in every module that has my schema/models module; including the `app` module.

My schema/models build.gradle.kts:
```kotlin
apollo {
    generateApolloMetadata.set(true)
//    useSchemaPackageNameForFragments.set(false)
    packageName.set("com.example.common.models")
    introspection {
        endpointUrl.set(Depends.Environments.debugBaseUrl)
        //schemaFile.set(file("src/main/graphql/com.example/schema.json"))
        schemaFile.set(file("schema.graphql"))
    }
    generateKotlinModels.set(true)
}
```

the `.graphqlconfig`:
```yaml
{
  "name": "Example GraphQL Schema",
  "schemaPath": "schema.graphql",
  "extensions": {
    "endpoints": {
      "Default GraphQL Endpoint": {
        "url": "https://example.com/graphql",
        "headers": {
          "user-agent": "GraphQL"
        },
        "introspect": true
      }
    }
  }
}
```

and my `schema.graphql` is in this path: root: common module -> models module -> src -> main -> graphql -> com -> example -> src -> HERE
