### ISSUE TITLE
Can't use custom SNAPSHOT version due to `checkApolloVersions` error

### ISSUE THREAD

**Issue by scana** [apollographql/apollo-kotlin#6315]
### Version

4.1.1-SNAPSHOT

### Summary

It seems that `checkApolloVersions` tasks gets two different version names when targeting a specific `SNAPSHOT` build, resulting in an error.

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':network:checkApolloVersions'.
> Apollo: All apollo versions should be the same. Found:
  [4.1.1-20241209.154106-39, 4.1.1-SNAPSHOT]
```

In order to reproduce, use any SNAPSHOT version from here: https://s01.oss.sonatype.org/content/repositories/snapshots/com/apollographql/apollo/apollo-compiler/4.1.1-SNAPSHOT/
```toml
[versions]
apollo = '4.1.1-20241209.154106-39'
[plugins]
apollo = { id = "com.apollographql.apollo", version.ref = "apollo" }
[libraries]
apollo-cache = { module = "com.apollographql.apollo:apollo-normalized-cache", version.ref = "apollo" }
apollo-db = { module = "com.apollographql.apollo:apollo-normalized-cache-sqlite", version.ref = "apollo" }
apollo-runtime = { module = "com.apollographql.apollo:apollo-runtime", version.ref = "apollo" }
apollo-testing = { module = "com.apollographql.apollo:apollo-testing-support", version.ref = "apollo" }
`````

Using `apollo = '4.1.1-SNAPSHOT` works fine.

One can disable the task to circumvent this issue temporarily:
```groovy
tasks.configureEach {
  if (it.name == "checkApolloVersions") {
    it.enabled = false
  }
}
```

### Logs

```
(Your logs here)
```
